apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: .dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: .dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 197780904448.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 197780904448.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 26c01f9b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
